### ISSUE TITLE
Error with Yourls 1.9

### ISSUE THREAD

**Issue by gehwissenlos** [nicwaller/yourls-domainlimit-plugin#6]
Hello,

after the update to Yourls version 1.9 I get an error:

PHP Fatal error: Uncaught BadMethodCallException: Class 'YOURLS\\Database\\YDB' does not have a method 'escape' in [.../includes/vendor/aura/sql/src/AbstractExtendedPdo.php]

The previous version worked fine.

The problem is the yourls_escape function in:
$url = yourls_escape( yourls_sanitize_url( $url) );

https://docs.yourls.org/development/database-queries.html#upgrade-your-code-for-1-7-3

**Comment by joseyaz** [comment]
I have the same problem, after updating to version 1.9.1, it has stopped blocking, it really breaks the site.
Thanks.

**Comment by ochse** [comment]
Unfortunately I don't get the solution for this problem. Does anyone have a clue?

**Comment by luanfernandes** [comment]
Just remove this on line 38:
`	$url = yourls_escape( yourls_sanitize_url( $url) );`

**Comment by ochse** [comment]
Thank you
